sonar.projectKey=docbridge_labreport-service
sonar.projectName=DocBridge Lab Report Service
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.js,**/*.spec.js

sonar.sourceEncoding=UTF-8

sonar.coverage.exclusions=**/*
