sonar.projectKey=docbridge_symptom-service
sonar.projectName=DocBridge Symptom Service
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.js,**/*.spec.js

sonar.sourceEncoding=UTF-8

sonar.coverage.exclusions=**/*
