sonar.projectKey=docbridge_ai-companion-service
sonar.projectName=DocBridge AI Companion Service
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.js,**/*.spec.js

sonar.sourceEncoding=UTF-8

sonar.coverage.exclusions=**/*
